In [4]:
import pandas as pd
import numpy as np

df = pd.read_csv("6svfo1.csv")

df

    patient_id          name   age  gender     city admission_date height_cm
0         P001           NaN  25.0       F   mumbai     15/01/2024       180
1         P002  Rahul Sharma  60.0       F    Delhi     2024/01/16       170
2         P003    Neha Singh  45.0       M   Mumbai     2024/01/16       150
3         P004    Neha Singh  60.0    Male  kolkata     15/01/2024       170
4         P005    Neha Singh  25.0    Male  kolkata     2024-01-15       180
..         ...           ...   ...     ...      ...            ...       ...
125       P006   Anita Verma  25.0       M   Mumbai     2024-01-15       150
126       P007    Neha Singh  25.0       F  kolkata     15/01/2024       150
127       P008     John Paul  60.0       F  Chennai     2024-01-15       160
128       P009           NaN  45.0       M   Mumbai     2024-01-15       150
129       P010  Rahul Sharma  60.0  Female  Chennai     2024/01/16       150

[130 rows x 7 columns]

In [5]:
df.head()

  patient_id          name   age gender     city admission_date height_cm
0       P001           NaN  25.0      F   mumbai     15/01/2024       180
1       P002  Rahul Sharma  60.0      F    Delhi     2024/01/16       170
2       P003    Neha Singh  45.0      M   Mumbai     2024/01/16       150
3       P004    Neha Singh  60.0   Male  kolkata     15/01/2024       170
4       P005    Neha Singh  25.0   Male  kolkata     2024-01-15       180

In [6]:
df.isnull().sum()

patient_id         0
name              23
age               24
gender             0
city               0
admission_date     0
height_cm          0
dtype: int64

In [7]:
df['gender'].replace('Male', 'M', inplace=True)
df['gender'].replace('Female', 'F', inplace=True)

df['gender']

C:\Users\Shreeyash R Kurupath\AppData\Local\Temp\ipykernel_33884\1730102020.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['gender'].replace('Male', 'M', inplace=True)
C:\Users\Shreeyash R Kurupath\AppData\Local\Temp\ipykernel_33884\1730102020.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['gender'].replace('Female', 'F', inplace=True)

0      F
1      F
2      M
3      M
4      M
      ..
125    M
126    F
127    F
128    M
129    F
Name: gender, Length: 130, dtype: object

In [8]:
df['city'].value_counts()

city
kolkata    30
mumbai     26
Mumbai     25
Chennai    25
Delhi      24
Name: count, dtype: int64

In [9]:
df['height_cm'].max()

'abc'

In [14]:
df['height_cm']=pd.to_numeric(df['height_cm'],errors='coerce')

In [15]:
df['height_cm'].fillna(df['height_cm'].mean(), inplace=True)

C:\Users\Shreeyash R Kurupath\AppData\Local\Temp\ipykernel_33884\1094149191.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['height_cm'].fillna(df['height_cm'].mean(), inplace=True)

In [16]:
df['height_cm']

0      180.0
1      170.0
2      150.0
3      170.0
4      180.0
       ...
125    150.0
126    150.0
127    160.0
128    150.0
129    150.0
Name: height_cm, Length: 130, dtype: float64

In [17]:
df['age'].fillna(df['age'].mean(), inplace=True)

C:\Users\Shreeyash R Kurupath\AppData\Local\Temp\ipykernel_33884\1503503937.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].mean(), inplace=True)

In [19]:
df['age'].min()

-5.0

In [20]:
df.loc[df['age'] < 0, 'age'] = pd.NA

In [21]:
df['age'].fillna(df['age'].mean())

0      25.0
1      60.0
2      45.0
3      60.0
4      25.0
       ...
125    25.0
126    25.0
127    60.0
128    45.0
129    60.0
Name: age, Length: 130, dtype: float64

In [22]:
df.groupby('gender')['height_cm'].mean()

gender
F    164.663462
M    165.772333
Name: height_cm, dtype: float64

In [23]:
df.groupby('city')['gender'].value_counts()

city     gender
Chennai  F         18
         M          7
Delhi    F         14
         M         10
Mumbai   M         17
         F          8
kolkata  M         17
         F         13
mumbai   F         15
         M         11
Name: count, dtype: int64

In [24]:
df.groupby('city')['height_cm'].max()

city
Chennai    180.0
Delhi      180.0
Mumbai     180.0
kolkata    180.0
mumbai     180.0
Name: height_cm, dtype: float64

In [25]:
df['gender'].value_counts()

gender
F    68
M    62
Name: count, dtype: int64