In [6]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
df= pd.read_csv(r"C:\Users\Tetra\Downloads\22yztw.csv")
df.head()

  record_id patient_id     diagnosis      bp  sugar_level  visit_cost
0      R101       P013  Hypertension  120/80        140.0        2000
1      R102       P105      Diabetes  120/80          NaN        2500
2      R103       P098  Hypertension    high        140.0        3000
3      R104       P038        Asthma  140/90          NaN        3000
4      R105       P040        Asthma  130/85          NaN        1500

In [7]:
df.tail()

    record_id patient_id     diagnosis      bp  sugar_level  visit_cost
115      R216       P081        Asthma    high        110.0        2500
116      R217       P033      Diabetes    high          NaN        1500
117      R218       P063  Hypertension  140/90          NaN        2000
118      R219       P011  Hypertension  130/85        180.0        2500
119      R220       P013  Hypertension    high        180.0        1500

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   record_id    120 non-null    object
 1   patient_id   120 non-null    object
 2   diagnosis    120 non-null    object
 3   bp           120 non-null    object
 4   sugar_level  85 non-null     float64
 5   visit_cost   120 non-null    int64
dtypes: float64(1), int64(1), object(4)
memory usage: 5.8+ KB

In [26]:
df.describe

<bound method NDFrame.describe of     record_id patient_id     diagnosis      bp  sugar_level  visit_cost
0        R101       P013  Hypertension  120/80   140.000000        2000
1        R102       P105      Diabetes  120/80   141.058824        2500
2        R103       P098  Hypertension  140/90   140.000000        3000
3        R104       P038        Asthma  140/90   141.058824        3000
4        R105       P040        Asthma  130/85   141.058824        1500
..        ...        ...           ...     ...          ...         ...
115      R216       P081        Asthma  140/90   110.000000        2500
116      R217       P033      Diabetes  140/90   141.058824        1500
117      R218       P063  Hypertension  140/90   141.058824        2000
118      R219       P011  Hypertension  130/85   180.000000        2500
119      R220       P013  Hypertension  140/90   180.000000        1500

[120 rows x 6 columns]>

In [10]:
df.isnull().sum()

record_id       0
patient_id      0
diagnosis       0
bp              0
sugar_level    35
visit_cost      0
dtype: int64

In [11]:
df["sugar_level"].fillna(df["sugar_level"].mean(), inplace= True)

C:\Users\Tetra\AppData\Local\Temp\ipykernel_9260\1742045647.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["sugar_level"].fillna(df["sugar_level"].mean(), inplace= True)

In [12]:
df.isnull().sum()

record_id      0
patient_id     0
diagnosis      0
bp             0
sugar_level    0
visit_cost     0
dtype: int64

In [13]:
df["diagnosis"].value_counts()

diagnosis
Diabetes        43
Hypertension    42
Asthma          35
Name: count, dtype: int64

In [14]:
df.groupby('diagnosis')['visit_cost'].mean()

diagnosis
Asthma          2242.857143
Diabetes        2220.930233
Hypertension    2392.857143
Name: visit_cost, dtype: float64

In [15]:
df.groupby("diagnosis")["sugar_level"].mean()

diagnosis
Asthma          139.566387
Diabetes        145.852257
Hypertension    137.394958
Name: sugar_level, dtype: float64

In [16]:
df["bp"]= df["bp"].replace("high",'140/90')
df["bp"]= df["bp"].replace("low",'90/60')

In [17]:
df['bp']

0      120/80
1      120/80
2      140/90
3      140/90
4      130/85
        ...
115    140/90
116    140/90
117    140/90
118    130/85
119    140/90
Name: bp, Length: 120, dtype: object

In [19]:
df.groupby('diagnosis')["bp"].value_counts()

diagnosis     bp
Asthma        140/90    20
              130/85     9
              120/80     6
Diabetes      140/90    28
              130/85     8
              120/80     7
Hypertension  140/90    19
              130/85    15
              120/80     8
Name: count, dtype: int64

In [20]:
df["sugar_level"].max()

np.float64(180.0)

In [21]:
df["sugar_level"].min()

np.float64(110.0)

In [22]:
df["visit_cost"].min()

np.int64(1500)

In [23]:
df["visit_cost"].max()

np.int64(3000)

In [24]:
df

    record_id patient_id     diagnosis      bp  sugar_level  visit_cost
0        R101       P013  Hypertension  120/80   140.000000        2000
1        R102       P105      Diabetes  120/80   141.058824        2500
2        R103       P098  Hypertension  140/90   140.000000        3000
3        R104       P038        Asthma  140/90   141.058824        3000
4        R105       P040        Asthma  130/85   141.058824        1500
..        ...        ...           ...     ...          ...         ...
115      R216       P081        Asthma  140/90   110.000000        2500
116      R217       P033      Diabetes  140/90   141.058824        1500
117      R218       P063  Hypertension  140/90   141.058824        2000
118      R219       P011  Hypertension  130/85   180.000000        2500
119      R220       P013  Hypertension  140/90   180.000000        1500

[120 rows x 6 columns]