In [ ]:
# Numpy

In [2]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
print(arr.ndim)

2

In [4]:
print(arr.shape)

(2, 3)

In [5]:
print(arr.size)

6

In [6]:
print(arr[arr % 2 == 0])

[2 4 6]

In [7]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]

In [8]:
print(np.zeros((3,2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]

In [9]:
print(np.ones(4))

[1. 1. 1. 1.]

In [10]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(np.concatenate([arr1, arr2]))

[1 2 3 4 5 6]

In [11]:
a = np.array([[1,2,3,4], [1,2,3,4]])
b = np.array([[5,6,7,8], [5,6,7,8]])

print(np.concatenate((a, b), axis=0))
print(np.concatenate((a, b), axis=1))

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]

In [12]:
a = np.array([1,2,3,4,5,6])

print(np.array_split(a,6))

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]

In [13]:
a = np.array([1,2,3,4,5])

In [14]:
print(np.max(a))

5

In [15]:
print(np.min(a))

1

In [16]:
print(np.mean(a))

3.0

In [17]:
print(np.median(a))

3.0

In [19]:
a = np.eye(3)

In [20]:
print(np.linalg.matrix_rank(a))

3

In [21]:
print(np.linalg.det(a))

1.0

In [22]:
print(np.trace(a))

3.0

In [ ]:
# Pandas

In [23]:
import pandas as pd
import numpy as np

d = {
    "S.No": np.array([1,2,3,4,5,6,7,7]),
    "Name": np.array(["Ajay","Nancy","Amrutha","Tanya","Rahul","Ankit","Raj","Raj"]),
    "Age": np.array([5,10,24,np.nan,15,np.nan,26,26]),
    "Weight": np.array([20,25,21,20,25,np.nan,70,70])
}

df = pd.DataFrame(d)

In [36]:
df

   S.No     Name   Age  Weight
0     1     Ajay   5.0    20.0
1     2    Nancy  10.0    25.0
2     3  Amrutha  24.0    21.0
3     4    Tanya   NaN    20.0
4     5    Rahul  15.0    25.0
5     6    Ankit   NaN     NaN
6     7      Raj  26.0    70.0
7     7      Raj  26.0    70.0

In [24]:
df.columns

Index(['S.No', 'Name', 'Age', 'Weight'], dtype='object')

In [25]:
df.shape

(8, 4)

In [26]:
df.size

32

In [27]:
df.head(2)

   S.No   Name   Age  Weight
0     1   Ajay   5.0    20.0
1     2  Nancy  10.0    25.0

In [28]:
df.tail(2)

   S.No Name   Age  Weight
6     7  Raj  26.0    70.0
7     7  Raj  26.0    70.0

In [29]:
df.isnull().sum()

S.No      0
Name      0
Age       2
Weight    1
dtype: int64

In [30]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
dtype: bool

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   S.No    8 non-null      int64
 1   Name    8 non-null      object
 2   Age     6 non-null      float64
 3   Weight  7 non-null      float64
dtypes: float64(2), int64(1), object(1)
memory usage: 388.0+ bytes

In [32]:
df.describe()

           S.No        Age     Weight
count  8.000000   6.000000   7.000000
mean   4.375000  17.666667  35.857143
std    2.263846   9.003703  23.419569
min    1.000000   5.000000  20.000000
25%    2.750000  11.250000  20.500000
50%    4.500000  19.500000  25.000000
75%    6.250000  25.500000  47.500000
max    7.000000  26.000000  70.000000

In [33]:
df["Name"].nunique()

7

In [34]:
df.nunique()

S.No      7
Name      7
Age       5
Weight    4
dtype: int64

In [35]:
df["Weight"]
df["Age"]

0     5.0
1    10.0
2    24.0
3     NaN
4    15.0
5     NaN
6    26.0
7    26.0
Name: Age, dtype: float64